version: '3.4'
volumes:
    prometheus_data: {}
    grafana_data: {}
services:
  rabbitmq:
    image: rabbitmq:3.8
    volumes:
      - ./rabbit.conf:/etc/rabbitmq/rabbitmq.conf
  worker:
    build: .
    image: &img worker
    command: [celery, worker, -BE, --app=worker.app]
    environment: &env      
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc
      - prometheus_multiproc_dir=/multiprocessing
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app
      - ./shared/prometheus:/multiprocessing
  webapp:
    build: .
    image: *img
    command: [python, prometheus_server.py]
    environment: *env
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app
      - ./shared/prometheus:/multiprocessing
    ports:
      - 5000:5000
  runner:
    build: .
    image: *img
    command: [python, runner.py]
    environment: *env
    depends_on:
      - rabbitmq
    volumes:
      - ./app:/app
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    expose:
      - 9090
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
  celery-default-stats:
    image: ovalmoney/celery-exporter
    ports:
      - 9540:9540
    environment:
      - CELERY_EXPORTER_BROKER_URL=amqp://guest:guest@rabbitmq:5672


